### ISSUE TITLE
Issue with accent character with json_encode

### ISSUE THREAD

**Issue by ezimuel** [zendframework/zend-expressive-session#26] opened 2018-08-27 13:28 UTC
It seems there's an issue with accent characters with `json_encode()` in `Zend\Expressive\Session::extractSerializableValue` see the original issue report in https://github.com/zendframework/zend-expressive-authentication/issues/33

**Comment by geerteltink** [comment] 2018-08-27 19:10
@mbourquin Can you please check what the exact data is that is stored in the session. I tried to reproduce it but couldn't:

```php
$session = new Session([]);
$session->set('user', [
    'username' => 'Îñţérñåţîöñåļîžåţîöñ',
    'roles'    => ['admin'],
    'details'  => ['test' => 'Îñţérñåţîöñåļîžåţîöñ'],
]);

var_dump($session->get('user'));

// Output
array(3) {
    'username' =>
    string(39) "Îñţérñåţîöñåļîžåţîöñ"
    'roles' =>
    array(1) {
        [0] =>
        string(5) "admin"
    }
    'details' =>
    array(1) {
        'test' =>
        string(39) "Îñţérñåţîöñåļîžåţîöñ"
    }
}
```

**Comment by geerteltink** [comment] 2018-08-27 19:19
I'm thinking the database table isn't using the correct charset or collate and not returning a valid UTF-8 string, which is required by json_encode.

**Comment by mbourquin** [comment] 2018-08-28 09:04
@xtreamwayz  You have right! Problem was the charset with the database... Thanks!

My auth config was like that:

``'authentication' => [
        'pdo' => [
            'dsn'   => 'mysql:host=xxx.xxx.xxx.xxx;dbname=my_db',
            'username' => 'myusername',
            'password' => 'mypassword',
            'table' => 'users',
            'field' => [
                'identity' => 'username',
                'password' => 'password',
            ],
            'driver_options' => [
                PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES \'UTF8\''
            ],
            'sql_get_roles'   => 'SELECT role FROM users WHERE username = :identity',
            'sql_get_details' => 'SELECT user_id,firstname FROM users WHERE username=:identity'         
        ],   
        'redirect' => '/login'
    ],``

But driver_option is not taken here.. I added **charset=utf8** to the dsn string, comment the driver_option and all is fine! 

``'dsn' => 'mysql:host=xxx.xxx.xxx.xxx;dbname=my_db;charset=utf8'``

You can close this issue... :)

**Comment by froschdesign** [comment] 2018-08-28 09:09
@mbourquin 
Since version 5.3.6 of PHP you can use `charset`.  Before this version `PDO::MYSQL_ATTR_INIT_COMMAND` was needed.

http://php.net/manual/en/ref.pdo-mysql.connection.php

**Closed as completed** 2018-08-28 09:15 UTC
